course_management_system/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ListTrainee, AddTrainee, UpdateTrainee, DeleteTrainee, CourseUpdate, CourseViewSet

router = DefaultRouter()
router.register(r'courses', CourseViewSet)  

urlpatterns = [
    path('trainees/', ListTrainee.as_view(), name='list-trainees'),
    path('trainees/add/', AddTrainee.as_view(), name='add-trainee'),
    path('trainees/<int:pk>/', UpdateTrainee.as_view(), name='update-trainee'),
    path('trainees/<int:pk>/delete/', DeleteTrainee.as_view(), name='delete-trainee'),
    path('courses/<int:pk>/', CourseUpdate, name='update-course'),
    path('', include(router.urls)), 
]

course_management_system/course_app/urls.py
from django.urls import path
from course_app.views import *

urlpatterns = [
    path("", course, name="course"),
    path("insert/", courseInsert, name="insert_course"),
    path("update/<int:id>/", courseUpdate, name="update_course"),
    path("delete/<int:pk>/", CourseDeleteView.as_view(), name="delete_course"),
]

course_management_system/course_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("trainee/", include("trainee_app.urls")),
    path("course/", include("course_app.urls")),
    path("register/", register, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("api/", include("api.urls")),
]

course_management_system/course_app/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    level = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()

course_management_system/trainee_app/models.py
from django.db import models
from course_app.models import Course


# Create your models here.
class Trainee(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    level = models.CharField(max_length=100)
    join_date = models.DateField()
    courses = models.ManyToManyField(Course, blank=True)

course_management_system/course_app/views.py
from django.shortcuts import render, redirect
from course_app.models import Course
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


# Create your views here.
@login_required(login_url="login")
def course(request):
    courses = Course.objects.all()
    return render(request, "course.html", {"courses": courses})


@login_required(login_url="login")
def courseInsert(request):
    if request.method == "POST":
        name = request.POST["courseName"]
        level = request.POST["courseLevel"]
        start = request.POST["courseStart"]
        end = request.POST["courseEnd"]
        Course.objects.create(name=name, level=level, start_date=start, end_date=end)
        return redirect("course")
    return render(request, "insert_course.html")


@login_required(login_url="login")
def courseUpdate(request, id):
    courseDetails = Course.objects.get(id=id)
    if request.method == "POST":
        name = request.POST["courseName"]
        level = request.POST["courseLevel"]
        start = request.POST["courseStart"]
        end = request.POST["courseEnd"]
        Course.objects.filter(id=id).update(
            name=name, level=level, start_date=start, end_date=end
        )
        return redirect("course")
    return render(request, "update_course.html", {"course": courseDetails})


@method_decorator(login_required(login_url="login"), name="dispatch")
class CourseDeleteView(DeleteView):
    model = Course
    template_name = "course_confirm_delete.html"  # Create this template
    success_url = reverse_lazy("course")  # Redirect after deletion


# def courseDelete(request, id):
#     Course.objects.filter(id=id).delete()
#     return redirect("course")

course_management_system/course_app/templates/course.html
{% extends 'base.html' %} {% block title %}Courses{% endblock %}
{% block header%}
<a class="nav-link" href="{% url 'home' %}">Home</a>
<a class="nav-link" href="{% url 'trainee' %}">Trainees</a>
<a class="nav-link active" href="{% url 'course' %}">Courses</a>
<a class="nav-link" href="{% url 'logout' %}">Logout</a>
{% endblock %} {% block content %}
<section>
    <h3 class="text-center mb-5">Courses Table</h3>
    <div class="col-md-12 mx-auto overflow-auto">
        <table class="table table-dark table-hover table-striped-columns text-center table align-middle">
            <thead>
                <tr class="text-center align-middle">
                    <th scope="col">ID</th>
                    <th scope="col" width="20%">Name</th>
                    <th scope="col">Level</th>
                    <th scope="col" width="15%">Start Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Trainees</th>
                    <th scope="col" width="15%">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <th scope="row">{{ course.id }}</th>
                    <td class="text-capitalize">{{ course.name }}</td>
                    <td class="text-capitalize">{{ course.level }}</td>
                    <td>{{ course.start_date }}</td>
                    <td>{{ course.end_date }}</td>
                    <td>{{ course.trainee_set.count }}</td>
                    <td>
                        <a href="{% url 'update_course' course.id %}" class="btn btn-success m-1">Edit</a>
                        <a href="{% url 'delete_course' course.id %}" class="btn btn-danger m-1">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <a href="{% url 'insert_course' %}" class="btn btn-success">Add New Course</a>
</section>
{% endblock %}

course_management_system/course_app/templates/course_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<section class="text-center mt-5">
    <h2 class="text-center fw-bold mb-5">Confirm Course Deletion</h2>
    <p class="fs-4 mb-4">Are you sure you want to delete course <strong class="text-decoration-underline">{{ object.name }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mx-2 px-4 py-2">Yes, delete</button>
        <a href="{% url 'trainee' %}" class="btn btn-primary px-4 py-2">No, Cancel</a>
    </form>
    {% endblock %}

course_management_system/course_app/templates/insert_course.html
{% extends 'base.html' %}
{% block title %}Add Course{% endblock %}
{% block header %}
<a class="nav-link active" href="{% url 'home' %}">Home</a>
{% if request.user.is_authenticated %}
<a class="nav-link" href="{% url 'trainee' %}">Trainees</a>
<a class="nav-link" href="{% url 'course' %}">Courses</a>
<a class="nav-link" href="{% url 'logout' %}">Logout</a>
{% else %}
<a class="nav-link" href="{% url 'login' %}">Login</a>
<a class="nav-link" href="{% url 'register' %}">Register</a>
{% endif %}
{% endblock %}
{% block content %}
<section>
    <h3 class="text-center mb-5">Insert New Course</h3>
    <form class="w-md-75 w-50 mx-auto" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="courseName" class="form-label">Course Name</label>
            <input type="text" class="form-control bg-dark-subtle focus-ring" id="courseName" name="courseName" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required />
        </div>
        <div class="mb-3">
            <label for="courseLevel" class="form-label">Course Level</label>
            <select class="form-select bg-dark-subtle focus-ring" id="courseLevel" name="courseLevel" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required>
                <option value="" selected disabled hidden>Choose Level</option>
                <option>Beginner</option>
                <option>Intermediate</option>
                <option>Advanced</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="courseStart" class="form-label">Start Date</label>
            <input type="date" class="form-control bg-dark-subtle focus-ring" id="courseStart" name="courseStart" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required />
        </div>
        <div class="mb-3">
            <label for="courseEnd" class="form-label">End Date</label>
            <input type="date" class="form-control bg-dark-subtle focus-ring" id="courseEnd" name="courseEnd" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required />
        </div>
        <button type="submit" class="d-block btn btn-success w-50 mx-auto">Add Course</button>
    </form>
</section>
{% endblock %}

course_management_system/course_app/templates/update_course.html
{% extends 'base.html' %}
{% block title %}Add Course{% endblock %}
{% block header %}
<a class="nav-link active" href="{% url 'home' %}">Home</a>
{% if request.user.is_authenticated %}
<a class="nav-link" href="{% url 'trainee' %}">Trainees</a>
<a class="nav-link" href="{% url 'course' %}">Courses</a>
<a class="nav-link" href="{% url 'logout' %}">Logout</a>
{% else %}
<a class="nav-link" href="{% url 'login' %}">Login</a>
<a class="nav-link" href="{% url 'register' %}">Register</a>
{% endif %}
{% endblock %}
{% block content %}
<section>
    <h3 class="text-center mb-5">Insert New Course</h3>
    <form class="w-md-75 w-50  mx-auto" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="courseName" class="form-label">Course Name</label>
            <input type="text" class="form-control bg-dark-subtle focus-ring" id="courseName" name="courseName" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required value="{{ course.name }}" />
        </div>
        <div class="mb-3">
            <label for="courseLevel" class="form-label">Course Level</label>
            <select class="form-select bg-dark-subtle focus-ring" id="courseLevel" name="courseLevel" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required>
                            <option value="Beginner" {% if course.level == "Beginner" %} selected {% endif %}>Beginner</option>
                            <option value="Intermediate" {% if course.level == "Intermediate" %} selected {% endif %}>Intermediate</option>
                            <option value="Advanced" {% if course.level == "Advanced" %} selected {% endif %}>Advanced</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="courseStart" class="form-label">Start Date</label>
            <input type="date" class="form-control bg-dark-subtle focus-ring" id="courseStart" name="courseStart" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required value="{{ course.start_date|date:'Y-m-d' }}" />
        </div>
        <div class="mb-3">
            <label for="courseEnd" class="form-label">End Date</label>
            <input type="date" class="form-control bg-dark-subtle focus-ring" id="courseEnd" name="courseEnd" style="--bs-focus-ring-color: rgba(var(--bs-success-rgb), 0.25);
                            --bs-focus-ring-x: 10px;
                            --bs-focus-ring-y: 10px;
                            --bs-focus-ring-blur: 4px" required value="{{ course.end_date|date:'Y-m-d' }}" />
        </div>
        <button type="submit" class="d-block btn btn-success w-50 mx-auto">Update Course</button>
    </form>
</section>
{% endblock %}